# Pandas
Pandas is a powerful, open-source Python library used primarily for data manipulation, analysis, and cleaning. Built on top of NumPy, it is a fundamental tool for data scientists and analysts because it makes working with structured data (like spreadsheets or SQL tables) fast and intuitive.

## Basic Data Structure in Pandas

pandas provides two types of classes for handling data:

1. `Series`: a one-dimensional labeled array holding data of any type such as integers, strings, Python objects etc.

2. `DataFrame`: a two-dimensional data structure that holds data like a two-dimension array or a table with rows and columns.

## What is Index

- In pandas, an Index is an immutable sequence used to store axis labels for Series and DataFrames. 
- It acts like an "address" for data, allowing it to identify, align, and retrieve specific rows or columns efficiently.

### Core Concepts
- **Purpose**: The pandas Index enables label-based access and ensures data stays aligned during operations (like adding two DataFrames with different row orders).
- **Immutability**: Once created, the values within an Index cannot be changed individually, though the entire Index can be replaced.
- **Default Index**: When we create a DataFrame without specifying one, pandas assigns a RangeIndex—an memory-efficient integer-based index starting at 0.

### Common Operations
- **Set Index**: Use `df.set_index('col1')` to turn an existing column into the row index.
- **Reset Index**: Use `df.reset_index()` to move the current index back into a column and return to a default integer index.
- **Check Uniqueness**: Use `df.index.is_unique` to verify if all labels are distinct.
- **MultiIndex**: A hierarchical index that allows multiple levels of labels on a single axis.

## To Configure the options/Settings:

- `pd.set_option('display.max_columns', 85)`
- `pd.set_option('display.max_rows', 50)`

## Important Methods and Properties:

- `pd.read_csv()` : কোন csv file read করতে হলে, use করা হয়। 
- `pd.DataFrame(dic)` : Converting Dictionary into Dataframes.
---
- `df.shape` : row count & column count জানা যায়
- `df.info()` : row count, column count, data type, non-null count of each column
- `df.columns`  : Shows All the Column Name.
- `df['col1'].value_counts()`   : Returns the Distinct Count of Distinct values for col1
---
- `df.head()` : only returns 5 rows
- `df.head(10)`  : Returns 10 rows
- `df.tail(10)`  : Returns Last 10 rows
---
- `df['col1']` : Return the value of col1 as Series.
- `df.col1`     : Also Returns the value of col1 as Series. But sometimes con cause conflict when method name and col name both are same.
- `df[['last', 'email']]` : Returns a dataframe with last & email col only.

### .iloc (Integer Location)

- `df.iloc[0]`  : Returns the 1st Row of the table as Series. Here each header works as an Index.
- `df.iloc[[0, 1]]` : Returns the 1st Two Rows of the table as dataframe.
- `df.iloc[[0 ,1], 2]`  : Returns the 1st Two Element of the 3rd Column.

### .loc (Labelled Location)

- `df.loc[0]`  : Returns the 1st Row of the table as Series. Here each header works as an Index.
- `df.loc[[0, 1]]` : Returns the 1st Two Rows of the table as dataframe.
- `df.loc[[0, 1], 'email']` : Returns the 1st Two Elements of the email column as Series.
- `df.loc[[0, 1], ['email', 'last']]` : Returns the 1st Two Elements of the email & last column as Dataframe.
- `df.loc[0:2, 'Hobbyist']` : Returns the 1st Three element of Hobbyist column.
- `df.loc[0:2, 'Hobbyist':'Employment']` : Returns the 1st Three element for Hobbyist To Employment column.

## Index Operations:

- `df.set_index('email')`   : Will temporarily set email column as Index.
- `df.set_index('email', inplace=True)`   : Will set email column as Index unless until we reset them.
- `df.index`    : Retrun all the elements/value of Indexed Column, and the indexed colulmn Name.
- `df.reset_index(inplace=True)`    : Reset Back to integer ranged Index
- `df = pd.read_csv('Data/survey_results_public.csv', index_col='Respondent')`  : We can specify the Index Column at the time of file Loading.
- `df.sort_index()` : Sort Index column in Asc.
- `df.sort_index(Ascending=False)` : Sort Index column in Desc.
- `df.sort_index(inplace=True)` : To make the Index Sorting Permanent.

In [93]:
import pandas as pd

df = pd.read_csv('Data/survey_results_public.csv')
schema_df = pd.read_csv('Data/survey_results_schema.csv')
pd.set_option('display.max_columns', 85)
pd.set_option('display.max_rows', 50)

In [94]:
df.columns

Index(['Respondent', 'MainBranch', 'Hobbyist', 'OpenSourcer', 'OpenSource',
       'Employment', 'Country', 'Student', 'EdLevel', 'UndergradMajor',
       'EduOther', 'OrgSize', 'DevType', 'YearsCode', 'Age1stCode',
       'YearsCodePro', 'CareerSat', 'JobSat', 'MgrIdiot', 'MgrMoney',
       'MgrWant', 'JobSeek', 'LastHireDate', 'LastInt', 'FizzBuzz',
       'JobFactors', 'ResumeUpdate', 'CurrencySymbol', 'CurrencyDesc',
       'CompTotal', 'CompFreq', 'ConvertedComp', 'WorkWeekHrs', 'WorkPlan',
       'WorkChallenge', 'WorkRemote', 'WorkLoc', 'ImpSyn', 'CodeRev',
       'CodeRevHrs', 'UnitTests', 'PurchaseHow', 'PurchaseWhat',
       'LanguageWorkedWith', 'LanguageDesireNextYear', 'DatabaseWorkedWith',
       'DatabaseDesireNextYear', 'PlatformWorkedWith',
       'PlatformDesireNextYear', 'WebFrameWorkedWith',
       'WebFrameDesireNextYear', 'MiscTechWorkedWith',
       'MiscTechDesireNextYear', 'DevEnviron', 'OpSys', 'Containers',
       'BlockchainOrg', 'BlockchainIs', 'BetterLife', 'ITperson', 'OffOn',
       'SocialMedia', 'Extraversion', 'ScreenName', 'SOVisit1st',
       'SOVisitFreq', 'SOVisitTo', 'SOFindAnswer', 'SOTimeSaved',
       'SOHowMuchTime', 'SOAccount', 'SOPartFreq', 'SOJobs', 'EntTeams',
       'SOComm', 'WelcomeChange', 'SONewContent', 'Age', 'Gender', 'Trans',
       'Sexuality', 'Ethnicity', 'Dependents', 'SurveyLength', 'SurveyEase'],
      dtype='str')

### Tasks:

- একটি dictionary তৈরী করা এবং তাকে dataframe এ convert করা।
- Select a column named last. Show the column data.

In [95]:
# Creating a Dictionary
people = {
    "first" : ["Corey", "Jane", "John"],
    "last" : ["Schafer", "Doe", "Doe"],
    "email" : ["abc@gmail.com", "def@gmail.com", "ghi@gmail.com"]
}

# Converting Dictionary into Dataframes
df_people = pd.DataFrame(people)

# showing col - last, and table
print(df_people['last'])
print(df_people)

0    Schafer
1        Doe
2        Doe
Name: last, dtype: str
   first     last          email
0  Corey  Schafer  abc@gmail.com
1   Jane      Doe  def@gmail.com
2   John      Doe  ghi@gmail.com

In [96]:
df_people.iloc[[0,1]]

   first     last          email
0  Corey  Schafer  abc@gmail.com
1   Jane      Doe  def@gmail.com

## Understanding Filtering:

- `df['last'] == 'Doe'` : Returns a Series containing only true and false depending upon the condition.

   ```filt = (df['last'] == 'Doe')
    df[filt]
    # Returns Only those records which fulfil the condition (TRUE)
    # Or we can Rewrite this as:
    df[df['last'] == 'Doe']```
    
- `df.loc[filt, 'email']`   : Returns all the element of email Column that fulfil the condition.
- `df['col1'].isin([list])`   : Will return True/False Series where col1 == [list]
- `df['col1'].str.contains('sky')`  : Will return True/False Series for col1 whether it contains 'sky' or not.
- `df['col1'].str.contains('sky', na=False)`  : Will return True/False Series for col1 whether it contains 'sky' or not. and will handle na Error if NAN value exists.

In [97]:
# Get all the Element of email Column where last = Doe AND first = John

filt = (df_people['last'] == 'Doe') & (df_people['first'] == 'John')
df_people.loc[filt, 'email']

2    ghi@gmail.com
Name: email, dtype: str

In [98]:
# Get all the Element of email Column where last = Schafer OR first = John

filt = (df_people['last'] == 'Schafer') | (df_people['first'] == 'John')
df_people.loc[filt, 'email']

0    abc@gmail.com
2    ghi@gmail.com
Name: email, dtype: str

In [99]:
# Get all the Element of email Column where email IS NOT {last = Schafer OR first = John}

filt = (df_people['last'] == 'Schafer') | (df_people['first'] == 'John')
df_people.loc[~filt, 'email']

1    def@gmail.com
Name: email, dtype: str

In [100]:
# Return all the records where ConvertedComp(SALARY) > 70000

high_salary = (df['ConvertedComp'] > 70000)
df[high_salary]

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
5,6,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Canada,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Mathematics or statistics,Taken an online course in programming or softw...,NaN,Data or business analyst;Data scientist or mac...,13,15,3,Very satisfied,Slightly satisfied,Very confident,No,Yes,I am not interested in new job opportunities,1-2 years ago,Write any code;Complete a take-home project;In...,No,Financial performance or funding status of the...,I heard about a job opportunity (from a recrui...,CAD,Canadian dollar,40000.0,Monthly,366420.0,15.00,There's no schedule or spec; I work on what se...,NaN,A few days each month,Home,A little above average,No,NaN,"Yes, it's not part of our process but the deve...",Not sure,I have little or no influence,Java;R;SQL,Python;Scala;SQL,MongoDB;PostgreSQL,PostgreSQL,Android;Google Cloud Platform;Linux;Windows,Android;Google Cloud Platform;Linux;Windows,NaN,NaN,Hadoop,Hadoop;Pandas;TensorFlow;Unity 3D,Android Studio;Eclipse;PyCharm;RStudio;Visual ...,Windows,I do not use containers,Not at all,NaN,No,Yes,No,YouTube,In real life (in person),Login,2011,A few times per month or weekly,Find answers to specific questions,Less than once per week,Stack Overflow was slightly faster,60+ minutes,Yes,I have never participated in Q&A on Stack Over...,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,28.0,Man,No,Straight / Heterosexual,East Asian,No,Too long,Neither easy nor difficult
8,9,I am a developer by profession,Yes,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,New Zealand,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,10 to 19 employees,"Database administrator;Developer, back-end;Dev...",12,11,4,Slightly satisfied,Slightly satisfied,Somewhat confident,No,Not sure,"I’m not actively looking, but I am open to new...",Less than a year ago,Write any code;Interview with people in peer r...,Yes,Financial performance or funding status of the...,I was preparing for a job search,NZD,New Zealand dollar,138000.0,Yearly,95179.0,32.00,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,Less than once per month / Never,Office,A little above average,"Yes, because I see value in code review",12.0,"Yes, it's not part of our process but the deve...",Not sure,I have some influence,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;P...,Bash/Shell/PowerShell;C;HTML/CSS;JavaScript;Ru...,DynamoDB;PostgreSQL;SQLite,PostgreSQL;Redis;SQLite,AWS;Docker;Heroku;Linux;MacOS;Slack,AWS;Docker;Heroku;Linux;MacOS;Slack;Other(s):,Express;Ruby on Rails;Other(s):,Express;Ruby on Rails;Other(s):,Node.js;Unity 3D,Node.js,Vim,MacOS,Development;Testing;Production,Not at all,An irresponsible use of resources,No,SIGH,Yes,Twitter,In real life (in person),Username,2013,Daily or almost daily,Find answers to specific questions;Contribute ...,3-5 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,NaN,23.0,Man,No,Bisexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult
12,13,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,10 to 19 employees,Data or business analyst;Database administrato...,17,11,8,Very satisfied,Very satisfied,NaN,NaN,NaN,I am not interested in new job opportunities,3-4 years ago,Complete a take-home project;Interview with pe...,Yes,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,90000.0,Yearly,90000.0,40.00,There is a schedule and/or spec (made by me or...,"Meetings;Non-work commitments (parenting, scho...",All or almost all the time (I'm full-time remote),Home,A little above average,"Yes, because I see value in code review",5.0,"No, but I think we should",Developers and management have nearly equal in...,I have a great deal of influence,Bash/Shell/PowerShell;HTML/CSS;JavaScript;PHP;...,Bash/Shell/PowerShell;HTML/CSS;JavaScript;Rust...,Couchbase;DynamoDB;Firebase;MySQL,Firebase;MySQL;Redis,Android;AWS;Docker;IBM Cloud or Watson;iOS;Lin...,Android;AWS;Docker;IBM Cloud or Watson;Linux;S...,Angular/Angular.js;ASP.NET;Express;jQuery;Vue.js,Express;Vue.js,Node.js;Xamarin,Node.js;TensorFlow,Vim;Visual Studio;Visual Studio Code;Xcode,Windows,Development;Testing;Production,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,Yes,Yes,Twitter,In real life (in person),Username,2011,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Somewhat more welcome now than last year,Tech articles written by other developers;Cour...,28.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
15,16,I am a developer by profession,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,United Kingdom,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",10,17,3,Very satisfied,Slightly satisfied,Somewhat confident,No,No,"I’m not actively looking, but I am open to new...",3-4 years ago,Interview with people in senior / management r...,Yes,"Languages, frameworks, and other technologies ...",I heard about a job opportunity (from a recrui...,GBP,Pound sterling,29000.0,Monthly,455352.0,40.00,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Distrac...,A few days each month,Home,Average,No,NaN,"No, but I think we should",Developers and management have nearly equal in...,I have some influence,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;T...,C#;HTML/CSS;JavaScript;TypeScript;WebAssembly;...,MongoDB;Microsoft SQL Server;MySQL,Elasticsearch;MongoDB;Microsoft SQL Server;SQLite,NaN,AWS;Google Cloud Platform;Microsoft Azure,Angular/Angular.js;ASP.NET;jQuery,Angular/Angular.js;ASP.NET;React.js,.NET;.NET Core;Node.js,.NET Core;Node.js;React Native,Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,A passing fad,No,SIGH,No,YouTube,Online,Username,2010,Multiple times per day,Find answers to specific questions;Learn how t...,Less than once per week,Stack Overflow was much faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,26.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult
21,22,I am a developer by profession,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,Some college/university study without earning ...,NaN,Taken an online course in programming or softw...,"10,000 or more employees","Data or business analyst;Designer;Developer, b...",35,12,18,Slightly satisfied,Very dissatisfied,Somewhat confident,No,No,"I’m not actively looking, but I am open to new...",More than 4 years ago,Interview with people in senior / management r...,No,Industry that I'd be working in;Financial perf...,I had a negative experience or interaction at ...,USD,United States dollar,103000.0,Yearly,103000.0,40.00,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Meeting...,"Less than half the time, but at least one day ...",Home,Average,No,NaN,"No, but I think we should","The CTO, CIO, or other management purchase new...",I have little or no influence,Bash/Shell/PowerShell;C++;HTML/CSS;JavaScript;...,Bash/Shell/PowerShell;C++;HTML/CSS;JavaScript;...,Elasticsearch;MySQL;Oracle;Redis,Elasticsearch;MySQL;Oracle;Redis,Docker;Linux;Raspberry Pi;Windows,Docker;Linux;Raspberry Pi;Windows,Angular/Angular.js;Ruby on Rails,Angular/Angular.js;Ruby on Rails,Node.js,Node.js,Sublime Text;Visual Studio;Visual Studio Code,Windows,"Outside of work, for personal projects",Not at all,NaN,Yes,Yes,Yes,Instagram,Online,Username,I don't remember,Daily or almost daily,Find answers to specific questions,3-5 times per week,Stack Overflow was much faster,0-10 minutes,Yes,A few times per week,Yes,"No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,47.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88323,88876,I am a developer by profession,Yes,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Received on-the-job training in software devel...,"10,000 or more employees","Developer, back-end;Developer, game or graphics",8,15,2,Very satisfied,Slightly satisfied,Somewhat confident,Yes,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,"Write code by hand (e.g., on a whiteboard)",No,Office environment or company culture;Remote w...,"My job status changed (promotion, new job, etc.)",USD,United States dollar,180000.0,Yearly,180000.0,40.00,There is a schedule and/or spec (made by me or...,Distracting work environment;Meetings;Time spe...,"Less than half the time, but at least one day ...",Office,Average,"Yes, because I see value in code review",3.0,"Yes, it's part of our process",Not sure,I have little or no influence,Bash/Shell/PowerShell;C#;HTML/CSS;Java;Python;...,C#;Java;Kotlin;Scala,DynamoDB;MySQL,DynamoDB,AWS;Linux;MacOS;Windows,Android;AWS;iOS;Linux;MacOS;Windows,NaN,NaN,Apache Spark;Hadoop;.NET Core;Unity 3D,Apache Spark;CryEngine;Hadoop;.NET;.NET Core;T...,IntelliJ;Notepad++;PyCharm;Sublime Text;Vim;Vi...,MacOS,I do not use containers,NaN,A passing fad,Yes,SIGH,Yes,Reddit,Neither,UserID,2011,A few times per month or weekly,Find answers to specific questions,1-2 times per week,Stack Overflow was much faster,60+ minutes,Yes,Less than once per month or monthly,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are","Yes, somewhat",A lot less welcome now than last year,NaN,23.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
88324,88877,I am a developer by profession,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,500 to 999 employees,Data scientist or machine learning specialist;...,31,18,28,Very satisfied,Very satisfied,Very confident,Yes,Yes,"I’m not actively looking, but I am open to new...",More than 4 years ago,Interview with people in senior / management r...,Yes,"Industry that I'd be working in;Languages, fra...",I heard about a job opportunity (from a recrui...,USD,United States dollar,239000.0,Weekly,2000000.0,45.00,There is a schedule and/or spec (made by me or...,Meetings;Not enough people for the workload,Less than once per month / Never,Office,Far above average,"Yes, because I see value in code review",5.0,"No, but I think we should",Developers and management have nearly equal in...,I have some influence,Bash/Shell/PowerShell;C;Clojure;HTML/CSS;Java;...,Bash/Shell/PowerShell;Clojure;HTML/CSS;Java;Ja...,Oracle,Oracle,Docker;iOS;Kubernetes;Linux;Slack;Windows;Othe...,Other(s):,Other(s):,Other(s):,Apache Spark,Apache Spark,Atom;Emacs;IntelliJ;IPython / Jupyter;PyCharm;...,Windows,Development;Testing;Production,Implementing cryptocurrency-based products,An irresponsible use of resources,Yes,Yes,No,Facebook,Online,Screen Name,NaN,A few times per month or weekly,Find answers to specific questions,Less than once per week,Stack Overflow was much faster,11-30 minutes,Yes,I have never participated in Q&A on Stack Over...,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Somewhat more welcome now than last year,Tech articles written by other developers;Cour...,48.0,Man,No,Straight / Heterosexual,South Asian,Yes,Too long,Neither easy nor difficult
88325,88878,I am a developer by profession,Yes,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,20 to 99 employees,"Developer, back-end;Developer, front-end;Devel...",12,14,3,Very satisfied,Very satisfied,Very confident,Yes,Yes,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,130000.0,Yearly,130000.0,40.00,There is a schedule and/or spec (made by me or...,"Non-work commitments (parenting, school work, ...",A few days each month,Office,Far above average,"Yes, because I see value in code review",3.0,"No, and I'm glad we don't",Developers and management have nearly equal in...,I have some influence,HTML/CSS;JavaScript;Scala;TypeScript,JavaScript;Rust;Scala;TypeScript,PostgreSQL,PostgreSQL,Slack,Slack,React.js;Other(s):,React.js;Other(s):,Node.js,Node.js,IntelliJ;Sublime Text;Visual Studio Code,MacOS,Production,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,Yes,Yes,Twitter,Online,Username,2010,Multiple times per day,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,0-10 minutes,Yes,A few times per week,Yes,"No, I've heard of them, but I am not part of a...","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,26.0,Man,No,Straight / Heterosexual,South Asian,No,Appropriate in length,Easy
88326,88879,I am a developer by profession,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Finland,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",20 to 99 employees,"Developer, desktop or enterprise applications;...",17,16,7,Slightly satisfied,Neither satisfied nor dissatisfied,Not at all confident,Not sure,I am already a manager,"I’m not actively looking, but I am open to new...",More than 4 years ago,Complete a take-home project;Interview with pe...,No,"Languages, frameworks, and other technologies ...",I had a negative experience or interaction at ...,EUR,European Euro,6000.0,Monthly,82488.0,37.75,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Distrac...,Less than once per month / Never,Home,Far above average,"Yes, because I see value in code review",10.0,"Yes, it's part of our process",Developers and management have nearly equal in...,I have little or no influence,Bash/Shell/PowerShell;C++;Python,C++,NaN,NaN,Android;Linux;Windows,Linux;Windows,NaN,NaN,NaN,TensorFlow;Unity 3D;Unreal Engine,Android Studio;Notepad++;Vim;Visual Studio,Windows,I do not use containers,Not at all,A passing fad,Yes,NaN,NaN,YouTube,Neither,Username,I don't remember,A few times per month or weekly,Find answers to specific questions,Less than once per week,Stack Overflow was slightly faster,60+ minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are","No, not at all",Not applicable - I did not use Stack Overflow ...,NaN,34.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
88329,88882,I am a developer by profession,Yes,Never,"OSS is, on average, of LOWER quality than prop...",Employed full-time,Netherlands,"Yes, full-time","Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Participated in online coding competitions (e....,100 to 499 employees,Academic researcher;Database administrator;Dev...,10,15,8,Slightly dissatisfied,Very dissatisfied,Not at all confident,Yes,Yes,"I’m not actively looking, but I am open to new...",Less than a year ago,Write any code;Complete a take-home project;In...,No,Office environment or company culture;Remote w...,I had a negative experience or interaction at ...,EUR,European Euro,42768.0,Monthly,588012.0,40.00,There is a schedule and/or spec (made by me or...,Distracting work environment;Lack of support f...,Less than once per month / Never,Home,Far above average,"Yes, because I see value in code review",5.0,"Yes, it's part of our process",Not sure,I have little or no influence,C#;HTML/CSS;Java;JavaScript;PHP;Python,C#;Java;JavaScript;PHP,MariaDB;PostgreSQL,MariaDB;PostgreSQL,Android;Arduino;Linux;Raspberry Pi;WordPress,Android;Arduino;Linux;Raspberry Pi;WordPress,jQuery;React.js,jQuery;React.js,Unity 3D,Unity 3D,Android Studio;IntelliJ;Notepad++;Vim;Visual S...,Linux-based,I do not use containers,Not at all,A passing fad,Yes,Yes,Yes,Instagram,Neither,Username,2009,A few times per week,Find answers to specific questions,3-5 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,NaN,NaN,Man,No,Straight / Heterosexual,White or of European descent,Yes,Too long,Easy

In [101]:
# Return a Table of these column: Country, LanguageWorkedWith, ConvertedComp and where ConvertedComp(SALARY) > 70000

high_salary = (df['ConvertedComp'] > 70000)
df.loc[high_salary, ['Country', 'LanguageWorkedWith', 'ConvertedComp']]

,Country,LanguageWorkedWith,ConvertedComp
5,Canada,Java;R;SQL,366420.0
8,New Zealand,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;P...,95179.0
12,United States,Bash/Shell/PowerShell;HTML/CSS;JavaScript;PHP;...,90000.0
15,United Kingdom,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;T...,455352.0
21,United States,Bash/Shell/PowerShell;C++;HTML/CSS;JavaScript;...,103000.0
...,...,...,...
88323,United States,Bash/Shell/PowerShell;C#;HTML/CSS;Java;Python;...,180000.0
88324,United States,Bash/Shell/PowerShell;C;Clojure;HTML/CSS;Java;...,2000000.0
88325,United States,HTML/CSS;JavaScript;Scala;TypeScript,130000.0
88326,Finland,Bash/Shell/PowerShell;C++;Python,82488.0
88329,Netherlands,C#;HTML/CSS;Java;JavaScript;PHP;Python,588012.0

In [102]:
# Retrun the Country Column for: United States, India, United Kingdom, Germany, Canada

# 1.create filter Statement:
var = ['United States', 'India', 'Germany', 'United Kingdom', 'Canada']
filt = df['Country'].isin(var)

# 2.display the result:
df.loc[filt, 'Country']

0        United Kingdom
3         United States
5                Canada
7                 India
9                 India
              ...
88859     United States
88863    United Kingdom
88864             India
88877     United States
88878            Canada
Name: Country, Length: 45008, dtype: str

In [103]:
# Task: Return the LanguageWorkedWith Column for those which contains 'Python'

# 1.Create filter statement:
filt = df['LanguageWorkedWith'].str.contains('Python', na=False)

# 2.Display result:
df.loc[filt, 'LanguageWorkedWith']

0                          HTML/CSS;Java;JavaScript;Python
1                                      C++;HTML/CSS;Python
3                                      C;C++;C#;Python;SQL
4              C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA
7        Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...
                               ...
88854    Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...
88860      Bash/Shell/PowerShell;C++;Python;Ruby;Other(s):
88865      Bash/Shell/PowerShell;HTML/CSS;Python;Other(s):
88872             C;C++;HTML/CSS;JavaScript;PHP;Python;SQL
88876                           HTML/CSS;JavaScript;Python
Name: LanguageWorkedWith, Length: 36443, dtype: str

## Topic : Updating Rows and Column (Modify Elements)

- `df.columns = ['newCol1', 'newCol2', 'newCol3']`    : Changes Column Header's Name (METHOD-1)
- `df.rename(columns={'oldCol1': 'newCol1', 'oldCol2': 'newCol2'})`   : Temporarily Changes Column Header's Name (METHOD-2)
- `df.rename(columns={'oldCol1': 'newCol1', 'oldCol2': 'newCol2'}, inplace=True)`   : Permanantly Changes Column Header's Name (METHOD-2)

In METHOD-1 we have to pass all the column headers name. whether we have to change it or not. we have redefine all the columns name.

In METHOD-2 We pass only the columns header name that has to change.

---
## Updating/Changing Rows Element:

- `df.loc[2] = ['elem2.1', 'elem2.2', 'elem2.3']` : Will update the 3rd Row. **Important Notes**- Have to pass every Row element whether old or new.
- `df.loc[2, ['col2', 'col3']] = ['elem2.2', 'elem2.3']`    : Will update specific series of element
- `df.at[2, 'col1'] = 'elem2.1'`    : Will update specific elements

---

- `df.at()` :  is an accessor used to get or set a single value in a DataFrame using label-based indexing. ???we can also use df.loc() then why df.at()???

### Key Differences

- ***Performance***: df.at is significantly faster than df.loc for scalar lookups because it has less overhead. If you are loop-setting or getting individual cells, use .at.
- ***Capability***: df.loc is much more versatile. It allows for slicing (e.g., df.loc[1:5, 'A':'C']) and filtering with boolean masks, which .at cannot do.
- ***Slicing Behavior***: Unlike standard Python slicing, df.loc is inclusive of the end label (e.g., df.loc['a':'c'] includes 'c').

---

- We can Loop Through each element or Series to make certain change

## Function Passing Method:
1. `df/series.apply()`  : The pandas `.apply()` method is a versatile tool used to apply a function along an axis of a DataFrame or to every element of a Series. It is often used for data transformations that aren't natively supported by built-in pandas methods. While powerful, `.apply()` is essentially a loop in disguise. 

  ### How it Works:

  - On a Series: It runs a function on every single value in the column.
  - On a DataFrame: It runs a function across entire rows or columns.axis=0 (default): Applies the function to each column.axis=1: Applies the function to each row.

2. `df/series.map()`  : `.map()` is a powerful tool used to transform data by applying a function, dictionary, or another Series to every element in a Series or DataFrame.

### Key Usage Scenarios:

- **Using a Dictionary (Series only)**: This is the most common way to substitute values (e.g., mapping category IDs to names).
- **Using a Function**: You can pass a Python function or a lambda to transform every value (e.g., squaring numbers or changing text case).
- **Handling Missing Values**: You can use the na_action='ignore' parameter to prevent the mapping from affecting NaN values.
- **Series.map()**: Operates on a single column. It can take a dictionary, a Series, or a function.
- **DataFrame.map()**: Operates on every element across the entire table simultaneously. This replaced the now-deprecated .applymap() method.


3. `applymap()` : has been deprecated
4. `df/series.replace()`  : method is used to swap out values in a Pandas DataFrame or Series dynamically. It is highly flexible, allowing for single value replacements, dictionary-based lookups, or pattern matching via regular expressions. Designed for replacing entire cell values (exact matches). It works on numbers, strings, and the whole DataFrame.

## Difference Between series.apply() and Series.map():

While they can achieve similar results, `Series.map()` and `Series.apply()` are not the same. The primary difference lies in what they accept as input and how they handle complex operations.

### Key Differences

1. **Input Types**:

- `Series.map()` accepts a function, a dictionary, or another Series. This makes it ideal for direct value substitution (e.g., changing 'A' to 1 using a dictionary).
- `Series.apply()` only accepts a function. It cannot take a dictionary or Series for direct mapping.

2. **Handling Arguments**:

- `Series.apply()` can take additional positional or keyword arguments (args and **kwargs) to pass to the function.
- `Series.map()` generally does not support passing extra arguments to the mapping function.

3. **NaN Handling**:

- `Series.map()` has a specific na_action parameter that allows you to ignore NaN values, preventing the function from being applied to them.
- `Series.apply()` does not have this specific parameter; it will apply the function to every element regardless of whether it is a null value.

4. **Performance**:

- `Series.map()` is often faster for simple element-wise transformations or dictionary-based replacements.
- `Series.apply()` is better suited for more complex logic that might involve conditions or external arguments.

In [104]:
# Task: Change column header of df_people

df_people.columns = ['first_name', 'last_name', 'email']
df_people

  first_name last_name          email
0      Corey   Schafer  abc@gmail.com
1       Jane       Doe  def@gmail.com
2       John       Doe  ghi@gmail.com

In [105]:
# Task1: make df_people column header AllUpperCase
# Task2: Replace Underscor with space for df_people Column Header
# we can use .str.replace() Method

# 1.Converting to All Uppercase
df_people.columns = [x.upper() for x in df_people.columns]

# 2. replace underscore with space
df_people.columns = df_people.columns.str.replace('_', ' ')
df_people

  FIRST NAME LAST NAME          EMAIL
0      Corey   Schafer  abc@gmail.com
1       Jane       Doe  def@gmail.com
2       John       Doe  ghi@gmail.com

In [106]:
# Task: Take them back to previous column header state.

# Replacing space with underscore
df_people.columns = df_people.columns.str.replace(' ', '_')

# Covert to lowercase
df_people.columns = [x.lower() for x in df_people.columns]

df_people

  first_name last_name          email
0      Corey   Schafer  abc@gmail.com
1       Jane       Doe  def@gmail.com
2       John       Doe  ghi@gmail.com

In [107]:
# Task: Change first_name to first and last_name to last for df_people column header

df_people.rename(columns={'first_name': 'first', 'last_name': 'last'}, inplace=True)
df_people

   first     last          email
0  Corey  Schafer  abc@gmail.com
1   Jane      Doe  def@gmail.com
2   John      Doe  ghi@gmail.com

In [108]:
# Task1: Change the 3rd rows of df_people to Pial | Shawkat | same as before
# Task2: Change the 2nd rows of df_people to Sara | Jerin | same as before
# Task3: Change the 1st rows of df_people to Pinky | same as before | same as before

df_people.loc[2] = ['Pial', 'Shawkat', 'ghi@gmail.com']
df_people.loc[1, ['first', 'last']] = ['Sara', 'Jerin']
df_people.at[0, 'first'] = 'Pinky'
df_people

   first     last          email
0  Pinky  Schafer  abc@gmail.com
1   Sara    Jerin  def@gmail.com
2   Pial  Shawkat  ghi@gmail.com

In [109]:
# Task1: change email column in df_people to all uppercase

df_people['email'] = df_people['email'].str.upper()
df_people

   first     last          email
0  Pinky  Schafer  ABC@GMAIL.COM
1   Sara    Jerin  DEF@GMAIL.COM
2   Pial  Shawkat  GHI@GMAIL.COM

In [110]:
# Task1: Find length of each element of 'email' column in df_people


df_people['email'].apply(len)

0    13
1    13
2    13
Name: email, dtype: int64

In [111]:
df_people

   first     last          email
0  Pinky  Schafer  ABC@GMAIL.COM
1   Sara    Jerin  DEF@GMAIL.COM
2   Pial  Shawkat  GHI@GMAIL.COM

In [112]:
# Task1: Create a function to lowerCase the string and pass that function to every element of email colulmn
# Task2: Permanantly make the element of email column to LowerCase

# Defining the Function
def makeLower(x):
    return x.lower()

# Applying the function to each element of email column. (Notes1: This is Temporary Transformation; Notes2: Pass the Fn without parenthesis)
df_people['email'].apply(makeLower)

# Permanently making all element of email column to lower case.
df_people['email'] = df_people['email'].apply(makeLower)

df_people

   first     last          email
0  Pinky  Schafer  abc@gmail.com
1   Sara    Jerin  def@gmail.com
2   Pial  Shawkat  ghi@gmail.com

In [113]:
# Task: By using lambda function Turn email-col-elements to Uppercase

df_people['email'] = df_people['email'].apply(lambda x: x.upper())
df_people

   first     last          email
0  Pinky  Schafer  ABC@GMAIL.COM
1   Sara    Jerin  DEF@GMAIL.COM
2   Pial  Shawkat  GHI@GMAIL.COM

In [114]:
# Task1: Find the length of each column series for df
df.apply(len)

# Task2: Find the length of each rows series for df
df.apply(len, axis=1)

0        85
1        85
2        85
3        85
4        85
         ..
88878    85
88879    85
88880    85
88881    85
88882    85
Length: 88883, dtype: int64

In [115]:
# Task1: Find the length of every element of df_people DataFrame
df_people.map(len)

# Task2: Lower the every element of df_people (Note: Temporary Transformation)
df_people.map(str.lower)

   first     last          email
0  pinky  schafer  abc@gmail.com
1   sara    jerin  def@gmail.com
2   pial  shawkat  ghi@gmail.com

In [116]:
df_people

   first     last          email
0  Pinky  Schafer  ABC@GMAIL.COM
1   Sara    Jerin  DEF@GMAIL.COM
2   Pial  Shawkat  GHI@GMAIL.COM

In [117]:
# Temporarily map first-col
df_people['first'].map({'Pinky': 1, 'Sara': 2})

0    1.0
1    2.0
2    NaN
Name: first, dtype: float64

In [118]:
# Temporarily replace first-col. And Examine the both output.
df_people['first'].replace({'Pinky': 1, 'Sara': 2})

0       1
1       2
2    Pial
Name: first, dtype: object

In [119]:
# Rename df column name- from ConvertedComp to SalaryUSD

df.rename(columns={'ConvertedComp': 'SalaryUSD'}, inplace=True)
df.head()

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,SalaryUSD,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [122]:

# In df-Hobbyist-col Change Yes/No to True/False

df['Hobbyist'] = df['Hobbyist'].replace({'Yes': True, 'No': False})
df

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,SalaryUSD,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,True,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,False,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",True,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,False,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,True,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88878,88377,NaN,True,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;JavaScript;Other(s):,C++;HTML/CSS;JavaScript;SQL;WebAssembly;Other(s):,Firebase;SQLite,Firebase;MySQL;SQLite,Linux,Google Cloud Platform;Linux,jQuery,jQuery;Vue.js,Node.js,React Native;Unity 3D;Unreal Engine,Atom;Visual Studio;Visual Studio Code,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,What?,YouTube,NaN,Username,I don't remember,A few times per week,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,I have never participated in Q&A on Stack Over...,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","No, not at all",NaN,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
88879,88601,NaN,False,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88880,88802,NaN,False,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88881,88816,NaN,False,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88882,88863,NaN,True,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,NaN,NaN,8,11,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript...,C;C++;C#;HTML/CSS;Java;Objective-C;SQL;Swift,DynamoDB;MariaDB;Microsoft SQL Server;MySQL,MariaDB;MySQL;Oracle;SQLite,iOS;Linux;MacOS;WordPress,Android;AWS;Google Cloud Platform;IBM Cloud or...,Django;jQuery;React.js,Django,Unity 3D;Unreal Engine,NaN,Android Studio;Atom;Eclipse;NetBeans;Notepad++...,Linux-based,Production,NaN,"Useful for decentralized currency (i.e., Bitcoin)",Yes,Also Yes,Yes,WhatsApp,In real life (in person),NaN,2012,Daily or almost daily,Find answers to specific questions;Learn how t...,6-10 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,Yes,"No, I've heard of them, but I am not part of a...","Yes, somewhat",Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy